# =============================================================================
# HEPCoverageKG: facet + signature parity against the acquisition repo
#
# The point of this file. We DERIVE the facet layer rather than importing
# upstream's frozen `pilot/analysis_facets.jsonl`, because the file is a
# 60-paper snapshot of a function and goes stale the moment paper 61 arrives.
# Deriving is only defensible if it reproduces the snapshot exactly — so the
# snapshot is kept as the ORACLE and compared against, card for card.
#
# Three guards, catching three different failures:
#   parity        -- our derivation drifts from upstream's        (the real one)
#   pinned hash   -- someone edits the vendored vocabulary here
#   port agreement-- our signature port drifts from upstream's module
#
# The last two need the reference repo on disk and skip cleanly without it, so
# CI and a fresh clone still run the suite. Parity needs only the committed
# fixture and therefore always runs.
# =============================================================================
from __future__ import annotations

import hashlib
import json
import os
import subprocess
import sys
from pathlib import Path

import pytest

from hepcoveragekg.facets import (
    CARD_FIELDS,
    SIGNATURES_SOURCE,
    VOCABULARY_SOURCE,
    signatures,
)
from hepcoveragekg.facets import derive as facets_derive
from hepcoveragekg.facets.vocabulary import canonicalize_entity, facet_tags

# The reference codebase is read-only and lives outside this repo (CLAUDE.md).
REFERENCE_REPO = Path(
    os.environ.get("HEPKG_REFERENCE_REPO", "../HEPKG_promopt_tests")
).expanduser()
FIXTURE = Path(__file__).parent / "fixtures" / "analysis_facets.jsonl"
CARD_FIELD_NAMES = sorted(set(CARD_FIELDS.values()))


def _gold() -> dict[str, dict]:
    if not FIXTURE.exists():
        pytest.skip(f"oracle fixture not committed: {FIXTURE}")
    rows = [json.loads(line) for line in FIXTURE.read_text().splitlines() if line.strip()]
    return {row["paper_id"]: row for row in rows}


def _real_db():
    """The pilot graph. Skipped rather than failed when absent: a fresh clone
    has no database, and the rest of the suite must still run."""
    db = Path("data/processed/hepkg.db")
    if not db.exists():
        pytest.skip("no pilot database at data/processed/hepkg.db")
    return facets_derive.connect(db)


# --- the vendored file is upstream's, byte for byte ---------------------------


def test_vendored_vocabulary_is_unmodified():
    """Catches a local edit to a file we do not own.

    `vocabulary.py` is copied verbatim so that parity means something. Editing
    it here would make our facets diverge from upstream's while every parity
    test still passed against a fixture generated by the edited code.
    """
    path = Path(facets_derive.__file__).with_name("vocabulary.py")
    digest = hashlib.sha256(path.read_bytes()).hexdigest()
    assert digest == VOCABULARY_SOURCE["sha256"], (
        "hepcoveragekg/facets/vocabulary.py has been modified. It is vendored "
        f"verbatim from {VOCABULARY_SOURCE['repo']}@{VOCABULARY_SOURCE['commit'][:8]}. "
        "Re-copy it and update VOCABULARY_SOURCE['sha256'] rather than editing."
    )


@pytest.mark.skipif(not REFERENCE_REPO.exists(), reason="reference repo not on this machine")
def test_vendored_vocabulary_matches_upstream_working_tree():
    """Catches upstream drift: they changed the tables, we are still on the old
    ones. A failure here is news, not a bug — re-vendor and re-run parity."""
    upstream = REFERENCE_REPO / "hepkg_acquisition" / "vocabulary.py"
    if not upstream.exists():
        pytest.skip("upstream vocabulary.py not checked out on this branch")
    ours = Path(facets_derive.__file__).with_name("vocabulary.py")
    if hashlib.sha256(upstream.read_bytes()).hexdigest() != VOCABULARY_SOURCE["sha256"]:
        pytest.skip("upstream working tree is on a different revision than we vendored")
    assert ours.read_bytes() == upstream.read_bytes()


# --- card parity: the derivation reproduces the oracle exactly ----------------


def test_every_pilot_card_matches_the_oracle():
    """All 60 cards, field for field. The headline guard."""
    gold = _gold()
    conn = _real_db()
    facets_derive.derive_facets(conn)

    mismatches: list[str] = []
    for paper_id, expected in sorted(gold.items()):
        actual = facets_derive.card(conn, paper_id)
        for field in CARD_FIELD_NAMES:
            if actual[field] != expected[field]:
                missing = set(expected[field]) - set(actual[field])
                extra = set(actual[field]) - set(expected[field])
                mismatches.append(f"{paper_id}.{field}: missing={sorted(missing)} extra={sorted(extra)}")

    assert not mismatches, "card parity broken:\n  " + "\n  ".join(mismatches[:20])


def test_card_carries_category_and_experiments_from_the_paper_table():
    gold = _gold()
    conn = _real_db()
    facets_derive.derive_facets(conn)
    for paper_id in list(sorted(gold))[:5]:
        card = facets_derive.card(conn, paper_id)
        assert card["category"] == gold[paper_id]["category"]
        assert card["experiments"] == gold[paper_id]["experiments"]


def test_the_supervisors_tier1_gold_answers_reproduce():
    """His Tier 1 questions are one filter each over the cards. If these drift,
    the questions he will grade us on have silently changed answers."""
    conn = _real_db()
    facets_derive.derive_facets(conn)
    cards = {pid: facets_derive.card(conn, pid) for pid in _gold()}

    q1 = {p for p, c in cards.items()
          if {"BJet", "MET"} <= set(c["objects"]) and c["category"] == "search"}
    assert len(q1) == 18                                    # gold: 18 papers

    q2 = {p for p, c in cards.items() if "ABCD" in c["background_methods"]}
    assert q2 == {"2004.01678", "2011.07812", "2012.01581",
                  "2404.06204", "2511.11853", "2604.27044"}

    q3 = {p for p, c in cards.items()
          if "HistFitter" in c["statistical_methods"] and "SUSY" in c["process_families"]}
    assert q3 == {"2006.05880", "2011.07812", "2106.01676", "2211.08028"}

    # Q5 is the trap: string-matching "Higgs" drowns in Higgs *process* papers.
    q5 = {p for p, c in cards.items() if "HiggsCandidate" in c["objects"]}
    assert q5 == {"2006.05880", "2504.13081"}


def _rows_in(conn, vocabulary):
    return conn.execute("SELECT COUNT(*) FROM entity_facet WHERE vocabulary = ?",
                        (vocabulary,)).fetchone()[0]


def test_derive_is_idempotent():
    """Counted WITHIN the vocabulary, not over the whole table.

    `entity_facet` holds more than one vocabulary now -- region roles derive on
    `region-roles-v1` so they can be rebuilt without touching the ported layer.
    Asserting on the table total would have made that a failure; asserting per
    vocabulary keeps idempotence AND proves the delete scope, which is the thing
    that could actually break."""
    conn = _real_db()
    first = facets_derive.derive_facets(conn)
    rows_after_first = _rows_in(conn, first["vocabulary"])
    second = facets_derive.derive_facets(conn)
    rows_after_second = _rows_in(conn, second["vocabulary"])
    assert first["rows"] == second["rows"] == rows_after_first == rows_after_second


def test_region_roles_derive_beside_the_ported_facets_without_disturbing_them():
    """The two derivations share a table and must not clobber each other."""
    conn = _real_db()
    facets_derive.derive_facets(conn)
    ported = _rows_in(conn, "facets-v1")

    first = facets_derive.derive_region_roles(conn)
    second = facets_derive.derive_region_roles(conn)
    assert first == second, "region-role derivation is not idempotent"
    assert _rows_in(conn, "region-roles-v1") == first["matched"]
    assert _rows_in(conn, "facets-v1") == ported, "region roles deleted ported rows"

    facets_derive.derive_facets(conn)
    assert _rows_in(conn, "region-roles-v1") == first["matched"], \
        "re-deriving the ported facets deleted the region roles"


def test_derive_never_touches_the_source_tables():
    conn = _real_db()
    before = tuple(
        conn.execute(f"SELECT COUNT(*) FROM {t}").fetchone()[0]
        for t in ("entity", "entity_occurrence", "assertion")
    )
    facets_derive.derive_facets(conn)
    facets_derive.derive_signatures(conn)
    after = tuple(
        conn.execute(f"SELECT COUNT(*) FROM {t}").fetchone()[0]
        for t in ("entity", "entity_occurrence", "assertion")
    )
    assert before == after
    # and no assertion gained a native signature
    assert conn.execute(
        "SELECT COUNT(*) FROM assertion WHERE signature IS NOT NULL").fetchone()[0] == 0


# --- coverage is a measurement, so pin it -------------------------------------


def test_coverage_is_reported_and_partial():
    """The facet vocabulary is closed, so it misses things. That is a finding,
    not a defect — but it must be visible, or a partial card reads as complete."""
    conn = _real_db()
    info = facets_derive.derive_facets(conn)
    coverage = info["coverage"]

    assert coverage["detector_object"]["missed"] > 0
    assert coverage["systematic_uncertainty"]["missed"] > 0
    # every facetable kind is accounted for
    assert set(coverage) == set(CARD_FIELDS)
    for kind, c in coverage.items():
        assert c["matched"] + c["missed"] == c["entities"], kind


def test_card_coverage_flags_what_a_card_leaves_out():
    conn = _real_db()
    facets_derive.derive_facets(conn)
    # 2006.05880 files its signal regions under detector_object, so its object
    # coverage is necessarily partial — the clearest case of a miss that is an
    # extraction problem rather than a vocabulary gap.
    coverage = facets_derive.card_coverage(conn, "2006.05880")
    assert coverage["detector_object"]["missed"] > 0
    assert coverage["detector_object"]["total"] > coverage["detector_object"]["matched"]


# --- signatures ---------------------------------------------------------------


def test_signature_synthesis_finds_the_one_or_group():
    """Gold Q8: 'exactly 2 electrons OR exactly 2 muons' — exactly one analysis
    in the whole corpus, 2001.06899, and it is the sharp OR-vs-AND test."""
    conn = _real_db()
    facets_derive.derive_signatures(conn)

    rows = conn.execute(
        "SELECT a.paper_id, d.signature FROM assertion_signature_derived d"
        "  JOIN assertion a ON a.assertion_id = d.assertion_id"
        " WHERE d.is_or_group = 1"
    ).fetchall()
    assert {r["paper_id"] for r in rows} == {"2001.06899"}

    trees = {r["signature"] for r in rows}
    assert len(trees) == 1, "every member of one OR group must share one tree"
    tree = json.loads(trees.pop())
    assert tree["operator"] == "any_of"
    assert len(tree["children"]) == 2
    assert all(child["operator"] == "object_count" for child in tree["children"])
    assert {child["comparator"] for child in tree["children"]} == {"=="}
    assert {child["value"] for child in tree["children"]} == {2}


def test_vetoes_without_a_count_default_to_zero():
    conn = _real_db()
    facets_derive.derive_signatures(conn)
    row = conn.execute(
        "SELECT d.signature FROM assertion_signature_derived d"
        "  JOIN assertion a ON a.assertion_id = d.assertion_id"
        " WHERE a.predicate = 'region_vetoes_object'"
        "   AND json_extract(a.qualifiers, '$.count') IS NULL LIMIT 1"
    ).fetchone()
    if row is None:
        pytest.skip("no count-less veto in this graph")
    tree = json.loads(row["signature"])
    assert tree["comparator"] == "==" and tree["value"] == 0


def test_signature_recall_is_bounded_by_the_extraction():
    """Not a quality bar — a recorded measurement. Synthesis can only recover
    counts the extractor actually wrote down, and most were never written."""
    conn = _real_db()
    info = facets_derive.derive_signatures(conn)
    assert info["native_signatures"] == 0          # the extraction produced none
    assert 0 < info["derived"] < info["candidates"]
    # the OR rule's only signal is present on a small minority
    assert info["with_subchannel_flag"] < info["candidates"] * 0.05


def _upstream_module(tmp_path_factory, *, revision, module, pkg_name, expected_sha):
    """Import one upstream module from GIT rather than from the working tree.

    The reference repo has feature branches checked in and out, so whichever
    branch happens to be checked out would otherwise decide whether these tests
    run — and the tests that validate our copies are exactly the ones that must
    not silently skip. Reading from the pinned revision removes the checkout
    from the equation.

    Each caller gets its OWN package name: two fixtures materialising different
    revisions under one name would collide in sys.modules, and the second would
    quietly import the first's files.
    """
    if not REFERENCE_REPO.exists():
        pytest.skip("reference repo not on this machine")
    pytest.importorskip("pydantic", reason="upstream models are pydantic")

    pkg = tmp_path_factory.mktemp(pkg_name) / pkg_name
    pkg.mkdir()
    (pkg / "__init__.py").write_text("")
    for name in ("models.py", f"{module}.py"):
        try:
            blob = subprocess.run(
                ["git", "show", f"{revision}:hepkg_acquisition/{name}"],
                cwd=REFERENCE_REPO, capture_output=True, text=True, check=True,
            ).stdout
        except (subprocess.CalledProcessError, FileNotFoundError):
            pytest.skip(f"cannot read {name} at {revision[:8]} from the reference repo")
        (pkg / name).write_text(blob)

    digest = hashlib.sha256((pkg / f"{module}.py").read_bytes()).hexdigest()
    assert digest == expected_sha, (
        f"{module}.py at {revision[:8]} is not what we recorded — re-check provenance")

    sys.path.insert(0, str(pkg.parent))
    try:
        import importlib
        yield importlib.import_module(f"{pkg_name}.{module}")
    finally:
        sys.path.remove(str(pkg.parent))
        for name in [m for m in sys.modules if m.startswith(pkg_name)]:
            del sys.modules[name]


@pytest.fixture(scope="module")
def upstream_signatures(tmp_path_factory):
    yield from _upstream_module(
        tmp_path_factory,
        revision=SIGNATURES_SOURCE["commit"],
        module="signatures",
        pkg_name="upstream_sig",
        expected_sha=SIGNATURES_SOURCE["sha256"],
    )


@pytest.fixture(scope="module")
def upstream_vocabulary(tmp_path_factory):
    yield from _upstream_module(
        tmp_path_factory,
        revision=VOCABULARY_SOURCE["commit"],
        module="vocabulary",
        pkg_name="upstream_vocab",
        expected_sha=VOCABULARY_SOURCE["sha256"],
    )


def test_port_agrees_with_upstream_on_every_leaf(upstream_signatures):
    """Our port takes SQLite rows, upstream's takes pydantic models. Same rules,
    so same verdict on every candidate — this is what makes the port
    trustworthy, and the only thing that will catch it drifting."""
    upstream = upstream_signatures
    conn = _real_db()

    checked = 0
    for cut in signatures.cuts_from_db(conn):
        ours = signatures.synthesize_signature(cut)

        predicate = next(
            (p for p in upstream._COUNT_PREDICATES if p.value == cut.predicate), None)

        class _A:  # duck-typed to the fields upstream's function reads
            signature = None
            object_id = cut.object_id
            qualifiers = cut.qualifiers

        _A.predicate = predicate
        theirs = upstream.synthesize_signature(_A())
        checked += 1

        if ours is None:
            assert theirs is None, f"{cut.assertion_id}: we declined, upstream did not"
        else:
            assert theirs is not None, f"{cut.assertion_id}: upstream declined, we did not"
            assert ours["comparator"] == theirs.comparator, cut.assertion_id
            assert ours["value"] == theirs.value, cut.assertion_id
            assert ours["range_max"] == theirs.range_max, cut.assertion_id
            assert ours["object_ref"] == theirs.object_ref, cut.assertion_id

    assert checked > 1000, "expected the whole candidate set, got a suspiciously small sample"


def test_port_agrees_with_upstream_on_the_or_grouping(upstream_signatures):
    """The OR rule is the one with real consequences — reading an AND as an OR
    makes a region look looser than it is and nothing downstream can tell."""
    upstream = upstream_signatures
    conn = _real_db()
    cuts = signatures.cuts_from_db(conn)

    theirs_input = []
    for cut in cuts:
        predicate = next(
            (p for p in upstream._COUNT_PREDICATES if p.value == cut.predicate), None)

        class _A:
            signature = None
            object_id = cut.object_id
            qualifiers = cut.qualifiers
            subject_id = cut.subject_id
            assertion_id = cut.assertion_id

        _A.predicate = predicate
        theirs_input.append(_A())

    ours = signatures.synthesize_or_groups(cuts)
    theirs = upstream.synthesize_or_groups(theirs_input)
    assert set(ours) == set(theirs)
    for assertion_id, tree in ours.items():
        mirror = theirs[assertion_id]
        assert mirror.operator.value == tree["operator"]
        assert len(mirror.children) == len(tree["children"])


def test_facet_functions_agree_with_upstream_on_every_label(upstream_vocabulary):
    """Every label in the graph, through both copies of the tables. Redundant
    while the vendored file is byte-identical — and the guard that catches it
    when it stops being.

    Runs over `entity_occurrence`, the labels the derivation actually sees.
    """
    upstream = upstream_vocabulary
    conn = _real_db()
    checked = 0
    for row in conn.execute("SELECT DISTINCT kind, label FROM entity_occurrence"):
        kind, label = row["kind"], row["label"]
        assert facet_tags(kind, label) == upstream.facet_tags(kind, label), label
        assert canonicalize_entity(kind, label) == upstream.canonicalize_entity(kind, label), label
        checked += 1
    assert checked > 1000, "expected every distinct label, got a suspiciously small sample"


# --- the prompt must not contain the answers -----------------------------------


def test_no_facet_value_leaks_into_the_schema_card():
    """The card lists field NAMES and coverage, never values.

    An earlier version listed every value in every field, and the values that
    read as most natural to include were five of the seven distinct keys in the
    supervisor's Tier 1 gold answers. A Tier 1 score under that card would have
    been partly measuring the prompt (D-054). This is the regression guard: it
    fails the moment anyone adds "a couple of examples".
    """
    from hepcoveragekg.query import schema_card

    conn = _real_db()
    facets_derive.derive_facets(conn)
    card = schema_card.render(conn)

    values = {r["value"] for r in conn.execute("SELECT DISTINCT value FROM entity_facet")}
    # Keys short enough to collide with ordinary English or with the notation
    # block are excluded: `MET` is a standard physics abbreviation the prompt
    # has always explained, and the coincidence with a facet key is not
    # something the card introduced.
    checkable = {v for v in values if len(v) > 4 and v not in {"Track", "Jet"}}
    leaked = sorted(v for v in checkable if v in card)
    assert not leaked, f"facet values present in the schema card: {leaked}"


def test_no_tier1_gold_key_leaks_into_the_purpose_prompt():
    """The hand-written prompt describes the facet layer without naming keys."""
    from hepcoveragekg.query import prompts

    gold = {"BJet", "ABCD", "HistFitter", "SUSY", "Unfolding", "HiggsCandidate"}
    leaked = sorted(k for k in gold if k in prompts.PURPOSE)
    assert not leaked, (
        f"Tier 1 gold keys in PURPOSE: {leaked}. Describe the layer, do not name "
        "its values -- search results supply the keys.")


def test_the_prefer_cheapest_route_line_is_not_in_the_default_prompt():
    """It exists as an ablation arm (C), not as the default (B). Which rung the
    agent picks is the thing being measured; instructing it deletes the result."""
    from hepcoveragekg.query import prompts

    assert prompts.PREFER_CHEAPEST_ROUTE not in prompts.PURPOSE
    assert "FACET TAGS" in prompts.PURPOSE_SECTIONS


def test_a_second_vocabulary_version_is_actually_written(tmp_path):
    """`vocabulary` exists so two versions can coexist and be diffed. The first
    implementation parameterised the DELETE but hardcoded the version in the
    INSERT, so asking for v2 reported "4594 rows" and wrote none of them --
    a silent no-op that looked like success."""
    import shutil

    src = Path("data/processed/hepkg.db")
    if not src.exists():
        pytest.skip("no pilot database")
    db = tmp_path / "two-vocabs.db"
    shutil.copy(src, db)
    conn = facets_derive.connect(db)

    facets_derive.derive_facets(conn, vocabulary="facets-v1")
    facets_derive.derive_facets(conn, vocabulary="facets-test")
    counts = dict(conn.execute(
        "SELECT vocabulary, COUNT(*) FROM entity_facet GROUP BY vocabulary"))
    assert counts.get("facets-test"), "the requested vocabulary was never written"
    assert counts["facets-test"] == counts["facets-v1"]
    # and re-deriving one version must not disturb the other
    facets_derive.derive_facets(conn, vocabulary="facets-v1")
    assert dict(conn.execute(
        "SELECT vocabulary, COUNT(*) FROM entity_facet GROUP BY vocabulary")) == counts
